In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd

from src.returns import ReturnCalculator

In [3]:
prices = pd.read_csv(
    "../data/raw/daily_prices.csv",
    index_col=0,
    parse_dates=True
)

prices.head()

            AAPL  AMZN  GOOGL    JNJ    JPM     KO   MSFT  NVDA  TSLA    XOM
Date
2010-06-29  7.68  5.43  11.28  37.64  24.61  15.64  17.58  0.24  1.59  31.59
2010-06-30  7.54  5.46  11.05  37.53  24.31  15.58  17.35  0.23  1.59  31.47
2010-07-01  7.45  5.55  10.92  37.53  23.99  15.55  17.47  0.24  1.46  31.22
2010-07-02  7.40  5.46  10.84  37.54  23.83  15.55  17.55  0.23  1.28  31.20
2010-07-06  7.45  5.50  10.83  37.54  24.16  15.67  17.97  0.23  1.07  31.69

In [4]:
prices.shape

(3936, 10)

In [6]:
calculator = ReturnCalculator()

In [7]:
simple_returns = calculator.simple_returns(prices)

simple_returns.head()

,AAPL,AMZN,GOOGL,JNJ,JPM,KO,MSFT,NVDA,TSLA,XOM
Date,,,,,,,,,,
2010-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-06-30,-0.018229,0.005525,-0.020390,-0.002922,-0.012190,-0.003836,-0.013083,-0.041667,0.000000,-0.003799
2010-07-01,-0.011936,0.016484,-0.011765,0.000000,-0.013163,-0.001926,0.006916,0.043478,-0.081761,-0.007944
2010-07-02,-0.006711,-0.016216,-0.007326,0.000266,-0.006669,0.000000,0.004579,-0.041667,-0.123288,-0.000641
2010-07-06,0.006757,0.007326,-0.000923,0.000000,0.013848,0.007717,0.023932,0.000000,-0.164062,0.015705

In [8]:
calculator.summary(simple_returns)

============================================================
RETURN SUMMARY
============================================================
Rows : 3936
Cols : 10

Missing Values
AAPL     1
AMZN     1
GOOGL    1
JNJ      1
JPM      1
KO       1
MSFT     1
NVDA     1
TSLA     1
XOM      1
dtype: int64

Mean Daily Returns
AAPL     0.001056
AMZN     0.001141
GOOGL    0.000997
JNJ      0.000531
JPM      0.000794
KO       0.000472
MSFT     0.000923
NVDA     0.002133
TSLA     0.002068
XOM      0.000516
dtype: float64

Daily Volatility
AAPL     0.017668
AMZN     0.020622
GOOGL    0.017411
JNJ      0.010704
JPM      0.017270
KO       0.010730
MSFT     0.016174
NVDA     0.029665
TSLA     0.036319
XOM      0.015794
dtype: float64

In [9]:
log_returns = calculator.log_returns(prices)

log_returns.head()

,AAPL,AMZN,GOOGL,JNJ,JPM,KO,MSFT,NVDA,TSLA,XOM
Date,,,,,,,,,,
2010-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-06-30,-0.018397,0.005510,-0.020601,-0.002927,-0.012265,-0.003844,-0.013169,-0.04256,0.000000,-0.003806
2010-07-01,-0.012008,0.016349,-0.011834,0.000000,-0.013251,-0.001927,0.006893,0.04256,-0.085298,-0.007976
2010-07-02,-0.006734,-0.016349,-0.007353,0.000266,-0.006692,0.000000,0.004569,-0.04256,-0.131576,-0.000641
2010-07-06,0.006734,0.007299,-0.000923,0.000000,0.013753,0.007687,0.023650,0.00000,-0.179201,0.015583

In [10]:
cumulative_returns = calculator.cumulative_returns(simple_returns.fillna(0))

cumulative_returns.head()

,AAPL,AMZN,GOOGL,JNJ,JPM,KO,MSFT,NVDA,TSLA,XOM
Date,,,,,,,,,,
2010-06-29,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2010-06-30,0.981771,1.005525,0.979610,0.997078,0.987810,0.996164,0.986917,0.958333,1.000000,0.996201
2010-07-01,0.970052,1.022099,0.968085,0.997078,0.974807,0.994246,0.993743,1.000000,0.918239,0.988287
2010-07-02,0.963542,1.005525,0.960993,0.997343,0.968306,0.994246,0.998294,0.958333,0.805031,0.987654
2010-07-06,0.970052,1.012891,0.960106,0.997343,0.981715,1.001918,1.022184,0.958333,0.672956,1.003166