In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd

from src.signals import SignalGenerator

In [3]:
prices = pd.read_csv(
    "../data/raw/daily_prices.csv",
    index_col=0,
    parse_dates=True
)

In [4]:
signal_engine = SignalGenerator()

In [5]:
weekly_returns = signal_engine.weekly_returns(prices)

weekly_returns.head()

,AAPL,AMZN,GOOGL,JNJ,JPM,KO,MSFT,NVDA,TSLA,XOM
Date,,,,,,,,,,
2010-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-07-09,0.051351,0.073260,0.071033,0.024774,0.083928,0.046945,0.042735,0.043478,-0.093750,0.039103
2010-07-16,-0.037275,0.010239,-0.016365,-0.018196,0.003871,0.000000,0.025683,-0.041667,0.189655,-0.014189
2010-07-23,0.040053,0.003378,0.065674,-0.030447,0.021597,0.045455,0.037294,0.043478,0.028986,0.030350
2010-07-30,-0.010270,-0.008418,-0.010682,0.007919,0.011325,0.006463,0.000000,-0.125000,-0.063380,-0.000607

In [6]:
rankings = signal_engine.rank_assets(
    weekly_returns
)

rankings.head()

            AAPL  AMZN  GOOGL   JNJ  JPM   KO  MSFT  NVDA  TSLA  XOM
Date
2010-07-02   NaN   NaN    NaN   NaN  NaN  NaN   NaN   NaN   NaN  NaN
2010-07-09   4.0   2.0    3.0   9.0  1.0  5.0   7.0   6.0  10.0  8.0
2010-07-16   9.0   3.0    7.0   8.0  4.0  5.0   2.0  10.0   1.0  6.0
2010-07-23   4.0   9.0    1.0  10.0  8.0  2.0   5.0   3.0   7.0  6.0
2010-07-30   7.0   6.0    8.0   2.0  1.0  3.0   4.0  10.0   9.0  5.0

In [7]:
signals = signal_engine.generate_long_short_signals(
    weekly_returns
)

signals.head()

            AAPL  AMZN  GOOGL  JNJ  JPM  KO  MSFT  NVDA  TSLA  XOM
Date
2010-07-02     0     0      0    0    0   0     0     0     0    0
2010-07-09     0     0      0    0    1   0     0     0    -1    0
2010-07-16     0     0      0    0    0   0     0    -1     1    0
2010-07-23     0     0      1   -1    0   0     0     0     0    0
2010-07-30     0     0      0    0    1   0     0    -1     0    0

In [8]:
signals.sum(axis=1).head()

Date
2010-07-02    0
2010-07-09    0
2010-07-16    0
2010-07-23    0
2010-07-30    0
Freq: W-FRI, dtype: int64

In [9]:
prices.columns

Index(['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM', 'KO', 'MSFT', 'NVDA', 'TSLA',
       'XOM'],
      dtype='object')